name: 'Helm Chart Publish to GitHub Pages'
description: 'Lints, packages, and publishes Helm chart to GitHub Pages using chart-releaser'

inputs:
  chart-path:
    description: 'Path to the Helm chart directory (e.g., sre/helm/backend)'
    required: true
  charts-repo-url:
    description: 'GitHub Pages URL for the charts repository'
    required: false
    default: 'https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}'
  skip-existing:
    description: 'Skip release if version already exists'
    required: false
    default: 'true'
  helm-version:
    description: 'Helm version to use'
    required: false
    default: 'v3.14.0'
  token:
    description: 'GitHub token for chart-releaser'
    required: true

outputs:
  chart-version:
    description: 'Version of the published chart'
    value: ${{ steps.get-version.outputs.version }}
  chart-name:
    description: 'Name of the published chart'
    value: ${{ steps.get-version.outputs.name }}

runs:
  using: "composite"
  steps:
    - name: Configure Git
      shell: bash
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

    - name: Install Helm
      uses: azure/setup-helm@v3
      with:
        version: ${{ inputs.helm-version }}

    - name: Add Helm Repositories for Dependencies
      shell: bash
      run: |
        if [ -f "${{ inputs.chart-path }}/Chart.yaml" ]; then
          if grep -q "^dependencies:" "${{ inputs.chart-path }}/Chart.yaml"; then
            echo "ðŸ“¦ Adding helm repositories for dependencies..."
            # Add the charts repository so chart-releaser can validate it
            helm repo add charts-repo ${{ inputs.charts-repo-url }} || true
            helm repo update
          fi
        fi

    - name: Build Chart Dependencies
      shell: bash
      run: |
        if [ -f "${{ inputs.chart-path }}/Chart.yaml" ]; then
          if grep -q "^dependencies:" "${{ inputs.chart-path }}/Chart.yaml"; then
            echo "ðŸ“¦ Building chart dependencies for ${{ inputs.chart-path }}..."
            helm dependency build ${{ inputs.chart-path }}
            echo "âœ… Chart dependencies built successfully"
          else
            echo "â„¹ï¸  No dependencies found in Chart.yaml"
          fi
        fi

    - name: Lint Helm Chart
      shell: bash
      run: |
        echo "ðŸ” Linting Helm chart at ${{ inputs.chart-path }}..."
        helm lint ${{ inputs.chart-path }}
        echo "âœ… Helm chart linting passed"

    - name: Get Chart Info
      id: get-version
      shell: bash
      run: |
        CHART_NAME=$(helm show chart ${{ inputs.chart-path }} | grep '^name:' | awk '{print $2}')
        CHART_VERSION=$(helm show chart ${{ inputs.chart-path }} | grep '^version:' | awk '{print $2}')

        echo "name=${CHART_NAME}" >> $GITHUB_OUTPUT
        echo "version=${CHART_VERSION}" >> $GITHUB_OUTPUT

        echo "ðŸ“¦ Chart: ${CHART_NAME}"
        echo "ðŸ·ï¸  Version: ${CHART_VERSION}"

    - name: Validate Chart Template
      shell: bash
      run: |
        echo "ðŸ” Validating Helm chart templates..."
        helm template test-release ${{ inputs.chart-path }} --dry-run > /dev/null
        echo "âœ… Helm chart templates are valid"

    - name: Run chart-releaser
      uses: helm/chart-releaser-action@v1.6.0
      with:
        charts_dir: $(dirname ${{ inputs.chart-path }})
      env:
        CR_TOKEN: ${{ inputs.token }}
        CR_SKIP_EXISTING: ${{ inputs.skip-existing }}

    - name: Summary
      shell: bash
      run: |
        echo "## ðŸ“¦ Helm Chart Published" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**Chart Name:** \`${{ steps.get-version.outputs.name }}\`" >> $GITHUB_STEP_SUMMARY
        echo "**Version:** \`${{ steps.get-version.outputs.version }}\`" >> $GITHUB_STEP_SUMMARY
        echo "**Repository:** ${{ inputs.charts-repo-url }}" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### ðŸ“¥ Install Command" >> $GITHUB_STEP_SUMMARY
        echo "\`\`\`bash" >> $GITHUB_STEP_SUMMARY
        echo "helm repo add my-charts ${{ inputs.charts-repo-url }}" >> $GITHUB_STEP_SUMMARY
        echo "helm repo update" >> $GITHUB_STEP_SUMMARY
        echo "helm install my-release my-charts/${{ steps.get-version.outputs.name }}" >> $GITHUB_STEP_SUMMARY
        echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
