name: 'Docker Build'
description: 'Builds multi-platform Docker images locally (no push to registry)'

inputs:
  context:
    description: 'Build context directory (e.g., ./backend)'
    required: true
  dockerfile:
    description: 'Path to Dockerfile relative to context (e.g., docker/Dockerfile)'
    required: false
    default: 'Dockerfile'
  platforms:
    description: 'Comma-separated list of target platforms (e.g., linux/amd64,linux/arm64)'
    required: false
    default: 'linux/amd64,linux/arm64'
  image-name:
    description: 'Image name (e.g., backend)'
    required: true
  image-tag:
    description: 'Image tag (e.g., 1.0.0-build.123-abc1234)'
    required: true
  build-args:
    description: 'Build arguments (key=value, one per line)'
    required: false
    default: ''
  load:
    description: 'Load image to local Docker (required for single-platform scanning)'
    required: false
    default: 'true'

outputs:
  image-ref:
    description: 'Full image reference with tag'
    value: ${{ steps.meta.outputs.image-ref }}
  digest:
    description: 'Image digest'
    value: ${{ steps.build.outputs.digest }}

runs:
  using: 'composite'
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Prepare image metadata
      id: meta
      shell: bash
      run: |
        IMAGE_REF="${{ inputs.image-name }}:${{ inputs.image-tag }}"

        echo "image-ref=${IMAGE_REF}" >> $GITHUB_OUTPUT

        echo "ðŸ·ï¸  Image reference: ${IMAGE_REF}"

    - name: Build Docker Image
      id: build
      uses: docker/build-push-action@v5
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.context }}/${{ inputs.dockerfile }}
        platforms: ${{ inputs.platforms }}
        tags: ${{ steps.meta.outputs.image-ref }}
        build-args: ${{ inputs.build-args }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        push: false
        load: ${{ inputs.load }}

    - name: Display build summary
      shell: bash
      run: |
        echo "## ðŸ³ Docker Image Build" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**Image:** \`${{ steps.meta.outputs.image-ref }}\`" >> $GITHUB_STEP_SUMMARY
        echo "**Platforms:** \`${{ inputs.platforms }}\`" >> $GITHUB_STEP_SUMMARY
        echo "**Built:** âœ… Success (local only, not pushed)" >> $GITHUB_STEP_SUMMARY
