name: 'Terraform and Terragrunt Setup'
description: 'Install and configure Terraform and Terragrunt with caching'

inputs:
  terraform-version:
    description: 'Terraform version'
    required: false
    default: '1.6.6'
  terragrunt-version:
    description: 'Terragrunt version'
    required: false
    default: '0.54.8'

runs:
  using: "composite"
  steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ inputs.terraform-version }}
        terraform_wrapper: false

    - name: Cache Terragrunt
      id: cache-terragrunt
      uses: actions/cache@v4
      with:
        path: /usr/local/bin/terragrunt
        key: terragrunt-${{ inputs.terragrunt-version }}

    - name: Install Terragrunt
      if: steps.cache-terragrunt.outputs.cache-hit != 'true'
      shell: bash
      run: |
        echo "📥 Installing Terragrunt ${{ inputs.terragrunt-version }}..."
        wget -q https://github.com/gruntwork-io/terragrunt/releases/download/v${{ inputs.terragrunt-version }}/terragrunt_linux_amd64
        chmod +x terragrunt_linux_amd64
        sudo mv terragrunt_linux_amd64 /usr/local/bin/terragrunt

    - name: Verify installations
      shell: bash
      run: |
        echo "✅ Terraform version:"
        terraform version
        echo ""
        echo "✅ Terragrunt version:"
        terragrunt --version

    - name: Summary
      shell: bash
      run: |
        echo "## Tools Installed" >> $GITHUB_STEP_SUMMARY
        echo "**Terraform:** ${{ inputs.terraform-version }}" >> $GITHUB_STEP_SUMMARY
        echo "**Terragrunt:** ${{ inputs.terragrunt-version }}" >> $GITHUB_STEP_SUMMARY
